### ISSUE TITLE
[BUG] Something went wrong installing the "sharp" module

### ISSUE THREAD

**Issue by Chiaki** [BobbyWibowo/lolisafe#136]
**Describe the bug**
After updating to 3a787ade6592e51eb374045f81c46b5d8609ddf6 service not starting.

**To Reproduce**
OS: Centos 7 | Node: 13.11.0 | Yarn: 1.22.4

**Expected behavior**
Service start after update.

**Additional context**
Log:
> Mar 12 18:59:54 host lolisafe: [2020-03-12 18:59:54] Uncaught Exception: Error:
Mar 12 18:59:54 host lolisafe: Something went wrong installing the "sharp" module
Mar 12 18:59:54 host lolisafe: /lib64/libstdc++.so.6: version "CXXABI_1.3.8" not found (required by /var/lolisafe/node_modules/sharp/build/Release/sharp.node)
Mar 12 18:59:54 host lolisafe: - Remove the "node_modules/sharp" directory then run
Mar 12 18:59:54 host lolisafe: "npm install --ignore-scripts=false --verbose" and look for errors
Mar 12 18:59:54 host lolisafe: - Consult the installation documentation at https://sharp.pixelplumbing.com/install
Mar 12 18:59:54 host lolisafe: - Search for this error at https://github.com/lovell/sharp/issues
Mar 12 18:59:54 host lolisafe: at Object.<anonymous> (/var/lolisafe/node_modules/sharp/lib/constructor.js:34:9)
Mar 12 18:59:54 host lolisafe: at Module._compile (internal/modules/cjs/loader.js:1147:30)
Mar 12 18:59:54 host lolisafe: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
Mar 12 18:59:54 host lolisafe: at Module.load (internal/modules/cjs/loader.js:996:32)
Mar 12 18:59:54 host lolisafe: at Function.Module._load (internal/modules/cjs/loader.js:896:14)
Mar 12 18:59:54 host lolisafe: at Module.require (internal/modules/cjs/loader.js:1036:19)
Mar 12 18:59:54 host lolisafe: at require (internal/modules/cjs/helpers.js:72:18)
Mar 12 18:59:54 host lolisafe: at Object.<anonymous> (/var/lolisafe/node_modules/sharp/lib/index.js:3:15)
Mar 12 18:59:54 host lolisafe: at Module._compile (internal/modules/cjs/loader.js:1147:30)
Mar 12 18:59:54 host lolisafe: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)

Currently I'm looking for a solution, maybe you could help faster. ^^

**Comment by BobbyWibowo** [comment]
> **DOWNGRADE sharp to v0.24.1 IF you are on RHEL/CentOS 7, at least for the time being**

https://github.com/BobbyWibowo/lolisafe/commit/3a787ade6592e51eb374045f81c46b5d8609ddf6#commitcomment-37727133

More info: https://github.com/lovell/sharp/issues/2119 (tldr; fixed on the upcoming v0.25.2).
