### ISSUE TITLE
[FEATURE REQUEST] User creation from dashboard

### ISSUE THREAD

**Issue by xaetacore** [BobbyWibowo/lolisafe#152]
**Describe the solution you'd like**
As you can disable user registration by setting it to private mode.

It would be nice to be able to add accounts in the dashboard as an admin user.

Something like this:
![Example Image](https://i.imgur.com/o1HlPN0.png)

**Comment by BobbyWibowo** [comment]
Makes sense. Certainly an important addition in private safes. I'll try to prioritize this whenever I'm free during the next few days.

**Comment by xaetacore** [comment]
> Makes sense. Certainly an important addition in private safes. I'll try to prioritize this whenever I'm free during the next few days.

Great ;3 
Would be rlly nice to see such a feature.

**Comment by BobbyWibowo** [comment]
Added in https://github.com/BobbyWibowo/lolisafe/commit/1c260c87b015c1fea53987bad6cf3a582ff9fdb3.
A bit rushed, so may not be fully stable. Feel free to re-open if buggy, or if you have any other ideas related to it.

![Preview 1](https://i.fiery.me/3RJSU.png)
![Preview 2](https://i.fiery.me/UpuX2.png)
![Preview 3](https://i.fiery.me/A6ebm.png)

All the other "new" bulk operation buttons and filter input are currently useless as they're still WIP.

**Comment by BobbyWibowo** [comment]
Password will be randomized if the input is empty. The same randomization used as when you randomize someone's password when editing their user account.

**Comment by xaetacore** [comment]
i see that superadmin doesn't have access to the user creation?

idk if its a bug or if you did it with a reason.
