### ISSUE TITLE
[BUG] User creation from dashboard

### ISSUE THREAD

**Issue by xaetacore** [BobbyWibowo/lolisafe#154]
**Describe the bug**
Recently you have added the possibility to create users from the dashboard on the private instances.

i've updated mine to the latest version but i can't add users somehow, the button doesn't appear at all for me. not as root and not as a newly created admin account.

**Comment by BobbyWibowo** [comment]
If it's the buttons not appearing, it sounds like outdated client assets, namely the dashboard.js file.

Anybody who have access to Manage Users menu, namely admins and superadmin, will definitely see the button as it wasn't hidden behind any permission check.
So if it doesn't appear anyway, then there's a high chance the codes are simply outdated.

Try to hard-reload the page (Ctrl+F5) or something.

**Comment by xaetacore** [comment]
Somehow CTRL+F5 didn't work but after like 5 or 10 minutes it worked. must have been CF their Cache :P 

Forgot what i said :P 

again thanks for adding this feature man <3 
issue closed lawl

**Comment by BobbyWibowo** [comment]
You may want to consider enabling `cacheControl` in config.js if you use CF (make sure CF integration is enabled as well; meaning the API key etc. are filled).
It'll enable Cache-Control tags I usually used with CF in safe.fiery.me.
By default, it'll make sure front-end pages are always up to date everytime you restart the node service, yet still cached by CF as long as necessary.

It's a bit of an advanced option however, as it may require further tweaks depending on your needs.
But it was certainly battle-tested in safe.fiery.me until I finally got banned 2mo ago, lmao

**Comment by xaetacore** [comment]
yea i was about to enable that, but i just recloned it bcs my other one was broken lmao but thnx for the tip
