### ISSUE TITLE
Regarding switching hosts

### ISSUE THREAD

**Issue by intelfierce** [BobbyWibowo/lolisafe#179]
Hi I am planning to switch my host is there any guide to switch domains and host without loosing any data.

**Comment by BobbyWibowo** [comment]
Just transfer the entire lolisafe directory as is.
All uploads and database are by default within the directory as well.
Then afterwards make sure to change the domain names in `config.js` file to match your new domains.

If you use Nginx, you shouldn't have to change anything other than the domain names as well.

**Comment by BobbyWibowo** [comment]
You will also have to purge `node_modules` sub-directory and run `yarn install` (or `yarn install --production`) again, if your new host is going to be using a different operating system or version.
Some of the dependencies are OS-dependant.
For good measures, do it anyway even if the OS is similar.

The database file itself is cross-platform though, so no need to worry about that.

**Comment by intelfierce** [comment]
would the existing links still be online after I change the host?

**Comment by BobbyWibowo** [comment]
Ja.
