### ISSUE TITLE
[FEATURE REQUEST] Docker compose

### ISSUE THREAD

**Issue by evanmn** [BobbyWibowo/lolisafe#184]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Add docker-compose file, with Nginx integrated. Possibly letsencrypt integration?

**Additional context**
If there is any interest in this I am happy to make one.

**Comment by BobbyWibowo** [comment]
I don't use Docker, so I wouldn't know how to make my own tbh.
Though, I believe I was informed in upstream that the current Dockerfile have issues, among other things. I wouldn't know myself, but PR is welcome!

**Comment by evanmn** [comment]
Definitely. current dockerfile is pulling from node 9 among other things. I'll send a pr in the next couple of days.

**Comment by evanmn** [comment]
I've made a pr updating and slimming the dockerfile. #186

**Comment by BobbyWibowo** [comment]
https://github.com/BobbyWibowo/lolisafe/pull/186 merged.
