### ISSUE TITLE
[FEATURE REQUEST] Manage Albums Admin Page

### ISSUE THREAD

**Issue by antiops** [BobbyWibowo/lolisafe#194]
**Describe the solution you'd like**
Similar to the manage users and uploads, it would be nice to have a page that displays the albums that have been created

**Additional context**
Format similar to the 'manage your albums' page but the admin page would include usernames + buttons/popup to modify it within the page

**Comment by BobbyWibowo** [comment]
Yeah, I was also thinking of implementing something like this someday, but too busy for it unfortunately.
Meanwhile you can use `albumid:` filter from Manage Uploads if you can find the album IDs (`select id, name from albums;`).
I was thinking of hooking the upcoming Manage Albums to it with that filter.
Just like how viewing user's uploads from Manage Users will instead open Manage Uploads with `user:` filter.
