### ISSUE TITLE
[FEATURE REQUEST] Option to choose field for filename in frontend

### ISSUE THREAD

**Issue by camjac251** [BobbyWibowo/lolisafe#198]
I would find this feature very useful since I was hoping to only use the randomly hashed filename to serve as a random url but it's used in the front end as well.

Could there be an option in the config to choose between originalfilename.ext and filename..ext?

It would also make searching easier I'd imagine.

**Comment by BobbyWibowo** [comment]
Closed https://github.com/BobbyWibowo/lolisafe/commit/8bcee712ac7e933de501c26327aaf8efce91897f.

**Comment by camjac251** [comment]
Thank you very much for implementing this

**Comment by BobbyWibowo** [comment]
And thanks for the support :tada:
