### ISSUE TITLE
[BUG] Front-End Upload Configuration Save Issue

### ISSUE THREAD

**Issue by WcLyic** [BobbyWibowo/lolisafe#211]
https://github.com/BobbyWibowo/lolisafe/blob/49ec795941374187b11f64aaa7475e8f800a3cce/src/js/home.js#L1046
`&& config[key].number &&` make the select option cannot be saved.

**Comment by BobbyWibowo** [comment]
Ah yes, regression from a commit I made a few days ago I think. Thanks, will get to it soonTM.
