### ISSUE TITLE
[Help] Deploying SSL

### ISSUE THREAD

**Issue by kaiser62** [BobbyWibowo/lolisafe#261]
Hello,
I am a complete noob while Deploying things like these. I was able to deploy it to a server but couldn't figure out how to configure SSL. I have valid certs but dunno how to use them. Could anyone help me?
Thanks.

**Comment by SD-Chargers** [comment]
The easiest, and accounting the sheer amount of tutorials for this, noob-friendliest way is to just deploy a reverse proxy infront of the setup, or am i wrong (@ everyone else) ?

In my case i used nginx for no particular reason.
You can either configure to deliver every file via Proxy or fully proxy everything to the node instance, which delivers the data via upstream. Last one is, again, the most noob-friendly way.

Use the Proxy to pass everything to the port of your node instance, while having the proxy configured as HTTPS with - for Example - LetsEncrypt for SSL.

If you need any pointers or example confs let me know, but imo you should read the docs of either node or webservers a bit longer.

**Comment by SD-Chargers** [comment]
@BobbyWibowo might wanna close this at the time speaking. If he needs any more hints, he'll reply :-)
