### ISSUE TITLE
[BUG] Element 'loading' not hides after album load.

### ISSUE THREAD

**Issue by Chiaki** [BobbyWibowo/lolisafe#293]
**Describe the bug**
Tested as root on latest commit. 
After click on album and page load 'loading' element (on right from album name) does not hide.

**To Reproduce**
1. As root, crate album.
2. Upload some content into album.
3. Go to dashboard and click on album link.

**Expected behavior**
'loading' element should hide after page load. Correct behavior 'Statistics' link in dashboard as example.

**Screenshots**
Sorry, can't provide.

**Additional context**
None

**Comment by BobbyWibowo** [comment]
I cannot reproduce this at all, with both root and user accounts. Tested on both local installation and safe.fiery.me, on both Firefox 82 and Chrome 86. On which device & browser did you encounter this issue? And have you tried force refreshing the page?

**Comment by Chiaki** [comment]
This bug works in Chrome 85.x (32-bit) and Firefox 78.x ESR (64-bit) with disabled cache on page refresh. User accounts also affected. Here a screenshoot from another account (user). Clicked on each album and happened this... https://i.imgur.com/mnRZBzt.jpg

**Comment by BobbyWibowo** [comment]
Yeah, definitely something on your end fam. Private installation? Have you rebuilt client assets? Are you behind a CDN like Cloudflare? Could be their cache. I've tried with Chrome 85 and Edge legacy (pre-Chromium era, from 2019). Couldn't reproduce on either.

**Comment by Chiaki** [comment]
No, it's public. No CDN. I can provide link if you need. Is this element behavior works by CSS, or any dependency?

**Comment by BobbyWibowo** [comment]
> Is this element behavior works by CSS, or any dependency?

The loading part in particular is strictly governed by `dashboard.js` only. And sure you can link me if that works for ya

**Comment by Chiaki** [comment]
Thanks for info. My `dashboard.js` should have no difference in comparison to PR. I'll try to figure out what happened.
[Here is my imouto](https://imouto.kawaii.su)

**Comment by BobbyWibowo** [comment]
Not sure if you've already "fixed" it within the past 2 hours or so, but I cannot reproduce the issue on your site either, lmao (only tried Firefox 82)

**Comment by Chiaki** [comment]
I've 'fix' it few min ago. Cleaning `dist` and rebuilding with `yarn build` solved issue (I guess). But before this, diff does not show any difference in `src` between PR and my copy. Weird... Sorry for bother. ^^"
