### ISSUE TITLE
[FEATURE REQUEST] Discord embedding / customizable Open Graph tags

### ISSUE THREAD

**Issue by soren11** [BobbyWibowo/lolisafe#323]
From the config creator, you'd be able to customize [Open Graph](https://ogp.me/) image tags for embedding on Discord.
(og:title, og:description, og:site_name, and "theme-color" all embed on Discord.)

**Comment by BobbyWibowo** [comment]
I need more details about this one. Which pages specifically that you want to have their Open Graph tags *better*?

Like, right off the bat, Open Graph tags are only applicable to HTML pages, meaning pages such as the homepage, auth page, FAQ, or album public pages.
For those examples above, we already have pretty decent Open Graph tags support built-in.

The following screenshots are taken on Discord:

**Homepage:**
![image](https://user-images.githubusercontent.com/9364930/100428455-910ae400-30c6-11eb-84db-bfece0f421c4.png)

**A public album:**
![image](https://user-images.githubusercontent.com/9364930/100428518-a3851d80-30c6-11eb-8ca0-4670302e9897.png)

Those are intended to be customized from within `views/_globals.njk`, and optionally `views/_layout.njk` for even more direct control.
https://github.com/BobbyWibowo/lolisafe/blob/13afe9a75e24654d11aef78df0c2b23b58f4b62b/views/_layout.njk#L32-L58

Making them to be customizable from the config file would be too cumbersome, so I was never against making changes directly to those two files, or more. After all, `git stash` is plenty reliable to stash your changes prior to pulling updates, then popping them back in.

**Comment by soren11** [comment]
I was actually referring to OG tags for the images themselves.  
![Vb32hW7xBr](https://user-images.githubusercontent.com/33104151/100429545-1658af00-305b-11eb-83cd-5b7dcc35a49f.png)
Which would be customizable by the user uploading the image. 
The viewer would be an HTML page including that'd include
 `<meta name="twitter:card" content="summary_large_image">`
`<meta id="discord" name="twitter:image" content="https://example.com/linktotherawimage.png">`

**Comment by BobbyWibowo** [comment]
Unfortunately something like that would require having a landing page for uploads, which we do not have.
The concept with this safe in particular is instead to share direct links to each uploads.

**Comment by soren11** [comment]
Alright, thanks
