### ISSUE TITLE
Split upload age option for registered and guests.

### ISSUE THREAD

**Issue by Chiaki** [BobbyWibowo/lolisafe#350]
Would be nice if admin could configure upload age option (automatically delete uploads after a certain amount of time) for registered users and guests separately. 
Example: guest can't configure upload age, registered user can choose from available options.

**Comment by BobbyWibowo** [comment]
Yeah, I've been wanting something similar for quite a while now. But I was also entertaining the thought of having dynamic upload age, at least specifically for non-registered, like the one being used in http://0x0.st/ (scroll down to their "file retention period" section).
I'm still mulling things through, and waiting for a bit more of a free time and drive to come around, but yeah, this'll go to my personal backlog.

**Comment by BobbyWibowo** [comment]
Implemented in https://github.com/BobbyWibowo/lolisafe/commit/2d147e748b85729b8c38740aa6eb51b09827ca39
