### ISSUE TITLE
.tar.zst being replaced as .zst

### ISSUE THREAD

**Issue by jomp16** [BobbyWibowo/lolisafe#370]
**Describe the bug**

When I upload a .tar.zst file, lolisafe changes to .zst, and needs to be renamed to .tar.zst to open the file.

**To Reproduce**

1. Upload a .tar.zst file
2. See the filename generated with wrong extension, .zst

**Expected behavior**

A file with .tar.zst like .tar.gz.

**Comment by BobbyWibowo** [comment]
Fixed in https://github.com/BobbyWibowo/lolisafe/commit/631d14d8872446f8e90c8b5acc4bd7be066dc368.
