### ISSUE TITLE
Show image URLs in Discord chat messages

### ISSUE THREAD

**Issue by AAAAAXfda-zz** [BobbyWibowo/lolisafe#373]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Option to enable **"Show Image URL"** for the image uploaded as shown in the screenshot below:

**Additional context**
No.

* **Screenshot**:
![image](https://user-images.githubusercontent.com/65740278/106373158-6451a200-637f-11eb-8d6a-a76773ceb7e5.png)

**Comment by BobbyWibowo** [comment]
To be honest with you, I don't really understand what you meant

**Comment by AAAAAXfda-zz** [comment]
> To be honest with you, I don't really understand what you meant

What I meant is, to have an option to show the URL for the captured image along with the image itself. **I was using the Social Media Platform "Discord" for this. Keep in mind this may/may NOT work with other social media platform(s).**

* **Example 2 :**

* **With _Show URL_ Option:**
![image](https://user-images.githubusercontent.com/65740278/106404903-04213580-643d-11eb-88e3-7d8bd468de0c.png)

* **Without _Show URL_ Option: (Image)**
![image](https://user-images.githubusercontent.com/65740278/106405005-65e19f80-643d-11eb-87dc-af9e32f9eeca.png)

**I was using Discord for this.**

**Comment by samstarnes** [comment]
I can tell you now, @AAAAAXfda, this won't be possible. Discord automatically hides the URL when a direct link to an image or video is posted. This was added to their patches not too long ago.
