### ISSUE TITLE
Chibi Image Source

### ISSUE THREAD

**Issue by Ksetrar** [BobbyWibowo/lolisafe#425]
I often uses your site for sharing images to my friends, it is quite sad to say goodbye but still I can tell managing such site sure causing financial issue moreover everyone got a life.
I will not brush anymore (though I am not doing)

I open this section, for asking if you can share the .png image of the characters on the website ?
like https://safe.fiery.me/render/miku/044.png

I like them much and I often refresh to that I can download the image

**Comment by BobbyWibowo** [comment]
Hi there, for that image specifically, I believe the source was this https://www.deviantart.com/racoonmx/art/Unfragment-Hatsune-Miku-Render-436514872

---

Initially I found it odd as to why I didn't keep a list of sources somewhere in the repository (I usually respect them at least that much for other things such as third-party JS libraries). But I remember now that it was due me actually mostly sourcing them from Google Images search, as they specifically had to be "renders", which were typically edited version of the original arts, to have the background removed and all that.

If you visit the DeviantArt one I linked, in the description you can see that the original art wasn't linked either (although it **could** have been their art too), but yeah, more often I just don't know the original arts either, so I ended up not linking their sources in the repository.

Anyways, I digress. If you want to try to reverse search other renders in the site, I recommend trying with SauceNAO, in addition to using Google Images reverse search, etc.

**Comment by Ksetrar** [comment]
Surely, a big credit should be given to those wonderful makers.
What I mean by image all chibi/images of your dying website only those image which comes during refreshing the website.

Example
https://safe.fiery.me/render/miku/042.png
etc, 

Edit.
If you ask why I need them, technically for no reason, I just want them to my collection

**Comment by BobbyWibowo** [comment]
Should have everything you need here https://safe.fiery.me/a/5iqdjBBq
Or a 7z-archive at https://i.fiery.me/QZDov.7z

**Comment by Ksetrar** [comment]
Sorry for the late reply
Thanks for sharing the images
