### ISSUE TITLE
Cannot access files uploaded to lolisafe

### ISSUE THREAD

**Issue by pansy27** [BobbyWibowo/lolisafe#445]
Hello.

I installed lolisafe by following the instructions for the production mode. After starting it, whenever i upload an image or video, it gets uploaded instantly. When i click on the  generated link, all i see is a blank 1x1 px image and a blank **chibisafe** page in case of videos. I've set **chibisafe** to manage uploads in my **config.js** file.

 I am also using **NextDNS** if that's relevant. I also cannot find a way to create an account on safe.fiery.me. I can only sign in using my new admin account on "**localhost:xxxx**". I am not using **nginx** and simply started lolisafe with `yarn start` after installation was complete. I am attaching my config file and screenshots of the problem i am facing below.

![ 7_30_10](https://user-images.githubusercontent.com/88635622/149644426-366deb15-0a45-4626-9ffb-17f102d4f103.png)

![ 7_30_46](https://user-images.githubusercontent.com/88635622/149644427-069f5521-a084-4b59-bf9b-6df3b1e87b89.png)

![ 7_31_10](https://user-images.githubusercontent.com/88635622/149644428-ee280aa9-2f10-4b6d-9b17-f820a820041e.png) 

 ^ The image i tried uploading.

![ 7_44_23](https://user-images.githubusercontent.com/88635622/149644699-c6f8b3af-7f2e-4306-a1bd-e36ddf47c987.png)

^ Terminal output on starting lolisafe. 

I also tried using the Firefox browser extension by adding my token to it but that also fails to connect to my album. 

Here's my config file: https://pastebin.com/CkkYc1ZK 

Sorry for the trouble.

**Comment by BobbyWibowo** [comment]
The screenshots confuse me a bit as they're seemingly mixed with chibisafe (a.k.a lolisafe v4) somehow?
My fork is based on lolisafe v3

> I am not using nginx and simply started lolisafe with yarn start after installation was complete

If you aren't using nginx, you need set to `serveFilesWithNode` to `true` in the config file, as the default config assumes you run this with nginx/apache/etc
You also need to change the `domain` to `http://localhost:PORT`, where PORT is the same as the `port` value in config, as long as your intention is to access it locally for the time being

> I also cannot find a way to create an account on safe.fiery.me

Yeah, my installation specifically is no longer open for public

**Comment by pansy27** [comment]
Thank you for the quick reply. Right as you said, i had set  **serveFilesWithNode** to true in my config file. I however, did not change the domain to my **localhost:port** so it was pointing to `https://lolisafe.moe` which is clearly a mistake on my part. On changing the port to **localhost:port**, the files are showing up as intended with their thumbnails. However since it's running on localport, only i can access the files. I tried changing the domain to `https://safe.fiery.me` but it gives an 404  error about resource not found. How can i make it so that the files i upload can be viewed by others too ? 
Sorry for the stupid question.

**Comment by BobbyWibowo** [comment]
> I tried changing the domain to https://safe.fiery.me but it gives an 404 error about resource not found.

That's normal, you're supposed to be using your own domain
This project is meant to be self-hosted, i.e. in your own server with your own domain

**Comment by pansy27** [comment]
I see. Thank you for helping me out. I'll close this issue now.
