### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'hasher')

### ISSUE THREAD

**Issue by breachedvince** [BobbyWibowo/lolisafe#488]
Can you help me with this error.

`[2022-05-06 22:20:52] TypeError: Cannot read properties of undefined (reading 'hasher')
    at /root/lolisafe/controllers/uploadController.js:575:42
    at async Promise.all (index 0)
    at async Object.self.actuallyFinishChunks (/root/lolisafe/controllers/uploadController.js:529:5)
    at async Object.self.finishChunks (/root/lolisafe/controllers/uploadController.js:511:5)

**Comment by BobbyWibowo** [comment]
Seems to be a relatively old commit, try updating

**Comment by breachedvince** [comment]
Ok.

**Comment by BobbyWibowo** [comment]
It's likely due to chunks temporary data timing out

The default timeout in config is 30 minutes
If someone happened to only finish uploading their chunks when the timer was about to run out, it could indeed potentially throw that error

If you can confirm it isn't something else, a temporary workaround is to simply increase the timeout
I'll add some potential fixes tomorrow

**Comment by breachedvince** [comment]
I am looking into my nginx error log and this is what is in there.
It is displaying a 524 error after/while it rebuilds chunks.

`
2022/05/06 22:32:40 [crit] 32154#32154: *426692 stat() "/lolisafestore/api/upload" failed (13: Permission denied), client: 172.70.54.13, server: domainnamehere.com, request: "POST /api/upload HTTP/1.1", host: "domainnamehere.com"
2022/05/06 22:33:00 [crit] 32154#32154: *426692 stat() "/lolisafestore/api/upload" failed (13: Permission denied), client: 172.70.54.13, server: domainnamehere.com, request: "POST /api/upload HTTP/1.1", host: "domainnamehere.com"
2022/05/06 22:33:21 [crit] 32154#32154: *426692 stat() "/lolisafestore/api/upload" failed (13: Permission denied), client: 172.70.54.13, server: domainnamehere.com, request: "POST /api/upload HTTP/1.1", host: "domainnamehere.com"
2022/05/06 22:33:42 [crit] 32154#32154: *426692 stat() "/lolisafestore/api/upload" failed (13: Permission denied), client: 172.70.54.13, server: domainnamehere.com, request: "POST /api/upload HTTP/1.1", host: "domainnamehere.com"
2022/05/06 22:34:02 [crit] 32154#32154: *426692 stat() "/lolisafestore/api/upload" failed (13: Permission denied), client: 172.70.54.13, server: domainnamehere.com, request: "POST /api/upload HTTP/1.1", host: "domainnamehere.com"
2022/05/06 22:34:22 [crit] 32154#32154: *426692 stat() "/lolisafestore/api/upload" failed (13: Permission denied), client: 172.70.54.13, server: domainnamehere.com, request: "POST /api/upload HTTP/1.1", host: "domainnamehere.com"
2022/05/06 22:34:43 [crit] 32154#32154: *426692 stat() "/lolisafestore/api/upload" failed (13: Permission denied), client: 172.70.54.13, server: domainnamehere.com, request: "POST /api/upload HTTP/1.1", host: "domainnamehere.com"
2022/05/06 22:35:03 [crit] 32154#32154: *426692 stat() "/lolisafestore/api/upload" failed (13: Permission denied), client: 172.70.54.13, server: domainnamehere.com, request: "POST /api/upload HTTP/1.1", host: "domainnamehere.com"
2022/05/06 22:35:23 [crit] 32154#32154: *426692 stat() "/lolisafestore/api/upload" failed (13: Permission denied), client: 172.70.54.13, server: domainnamehere.com, request: "POST /api/upload HTTP/1.1", host: "domainnamehere.com"
2022/05/06 22:35:44 [crit] 32154#32154: *426692 stat() "/lolisafestore/api/upload" failed (13: Permission denied), client: 172.70.54.13, server: domainnamehere.com, request: "POST /api/upload HTTP/1.1", host: "domainnamehere.com"
2022/05/06 22:36:04 [crit] 32154#32154: *426692 stat() "/lolisafestore/api/upload" failed (13: Permission denied), client: 172.70.54.13, server: domainnamehere.com, request: "POST /api/upload HTTP/1.1", host: "domainnamehere.com"
2022/05/06 22:36:24 [crit] 32154#32154: *426692 stat() "/lolisafestore/api/upload" failed (13: Permission denied), client: 172.70.54.13, server: domainnamehere.com, request: "POST /api/upload HTTP/1.1", host: "domainnamehere.com"
2022/05/06 22:36:46 [crit] 32154#32154: *426692 stat() "/lolisafestore/api/upload" failed (13: Permission denied), client: 172.70.54.13, server: domainnamehere.com, request: "POST /api/upload HTTP/1.1", host: "domainnamehere.com"
2022/05/06 22:37:06 [crit] 32154#32154: *426692 stat() "/lolisafestore/api/upload" failed (13: Permission denied), client: 172.70.54.13, server: domainnamehere.com, request: "POST /api/upload HTTP/1.1", host: "domainnamehere.com"
2022/05/06 22:37:27 [crit] 32154#32154: *426692 stat() "/lolisafestore/api/upload" failed (13: Permission denied), client: 172.70.54.13, server: domainnamehere.com, request: "POST /api/upload HTTP/1.1", host: "domainnamehere.com"
2022/05/06 22:37:47 [crit] 32154#32154: *426692 stat() "/lolisafestore/api/upload" failed (13: Permission denied), client: 172.70.54.13, server: domainnamehere.com, request: "POST /api/upload HTTP/1.1", host: "domainnamehere.com"
2022/05/06 22:38:07 [crit] 32154#32154: *426692 stat() "/lolisafestore/api/upload" failed (13: Permission denied), client: 172.70.54.13, server: domainnamehere.com, request: "POST /api/upload HTTP/1.1", host: "domainnamehere.com"
2022/05/06 22:38:28 [crit] 32154#32154: *426692 stat() "/lolisafestore/api/upload" failed (13: Permission denied), client: 172.70.54.13, server: domainnamehere.com, request: "POST /api/upload HTTP/1.1", host: "domainnamehere.com"
2022/05/06 22:38:48 [crit] 32154#32154: *426692 stat() "/lolisafestore/api/upload" failed (13: Permission denied), client: 172.70.54.13, server: domainnamehere.com, request: "POST /api/upload HTTP/1.1", host: "domainnamehere.com"
2022/05/06 22:39:09 [crit] 32154#32154: *426692 stat() "/lolisafestore/api/upload" failed (13: Permission denied), client: 172.70.54.13, server: domainnamehere.com, request: "POST /api/upload HTTP/1.1", host: "domainnamehere.com"
2022/05/06 22:39:31 [crit] 32154#32154: *426692 stat() "/lolisafestore/api/upload" failed (13: Permission denied), client: 172.70.54.13, server: domainnamehere.com, request: "POST /api/upload HTTP/1.1", host: "domainnamehere.com"
2022/05/06 22:39:52 [crit] 32154#32154: *426692 stat() "/lolisafestore/api/upload" failed (13: Permission denied), client: 172.70.54.13, server: domainnamehere.com, request: "POST /api/upload HTTP/1.1", host: "domainnamehere.com"
2022/05/06 22:40:15 [crit] 32154#32154: *426692 stat() "/lolisafestore/api/upload" failed (13: Permission denied), client: 172.70.54.13, server: domainnamehere.com, request: "POST /api/upload HTTP/1.1", host: "domainnamehere.com"
2022/05/06 22:40:36 [crit] 32154#32154: *426692 stat() "/lolisafestore/api/upload" failed (13: Permission denied), client: 172.70.54.13, server: domainnamehere.com, request: "POST /api/upload HTTP/1.1", host: "domainnamehere.com"
2022/05/06 22:40:55 [crit] 32154#32154: *426692 stat() "/lolisafestore/api/upload" failed (13: Permission denied), client: 172.70.54.13, server: domainnamehere.com, request: "POST /api/upload HTTP/1.1", host: "domainnamehere.com"
2
`

**Comment by breachedvince** [comment]
I'm on a VPN so the IP doesn't matter if your worrying!

**Comment by BobbyWibowo** [comment]
I think you probably misconfigured that domain in your nginx config

For some reason nginx thinks `domainnamehere.com/api/upload` is a static path located at `/lolisafestore/api/upload`

If it was lolisafe itself that was having a file permission issue, you basically wouldn't be seeing that on your nginx logs (at most you'd see it reporting that the request ended with http error code 500 or equivalent), since nginx is simply routing the requests from clients to/from lolisafe

---

Meaning it's likely unrelated with the undefined hasher errors

**Comment by breachedvince** [comment]
Keep in mind this is only for files 2gb> all the other files that are like 900mb or 1gb work perfectly fine.

**Comment by breachedvince** [comment]
Update: No more hasher errors after updating. Its failing to send the last POST request to api/uploads/finishchunks. Maybe you could try to upload something 1GB and see if it works.

**Comment by BobbyWibowo** [comment]
Tested some files ranging from ~1.8GB to ~7.84GB at 95MB chunk size (the latter was split up to 89 chunks), all worked fine

Re-uploaded the latter to test if hasher still worked properly with files that size, and it did indeed detect duplicate properly

---

~22GB file at 1MB chunk size just for the heck of it
![image](https://i.fiery.me/IyLj.png)
This later succeeded

**Comment by breachedvince** [comment]
Hmm, I will just re-install/ redo all my configs and lolisafe you can close this.
