### ISSUE TITLE
Add more upload size for certain groups.

### ISSUE THREAD

**Issue by breachedvince** [BobbyWibowo/lolisafe#489]
I like how you added stuff for certain ranks `vip, vvip` is it possible to make it so for example the group `vvip` gets like a 10gb upload size instead of 5 etc?

**Comment by breachedvince** [comment]
Maybe you could add automatic database backups too.

**Comment by BobbyWibowo** [comment]
> I like how you added stuff for certain ranks `vip, vvip` is it possible to make it so for example the group `vvip` gets like a 10gb upload size instead of 5 etc?

This may come one day, but don't forget that this fork is now on maintenance-only status

I'll only implement new features if I happen to have sudden needs for them, just like the retention periods separation

So I'll be closing this for now

If I suddenly have a need for it in the future, and implement it, I may notify you through this issue

**Comment by BobbyWibowo** [comment]
> Maybe you could add automatic database backups too.

I'm honestly on the opinion that it's better to use an external backups utility to simply backup the entire lolisafe directory anyways
