### ISSUE TITLE
Problem with the waveform

### ISSUE THREAD

**Issue by perdedora** [BobbyWibowo/lolisafe#503]
I was trying to set up the player for playing flac (error was nginx not serving mimetype), and after some tests I realized the waveform isn't working on firefox 100.0.2 and when it works (on chrome) isn't responsive messing the whole player.

**Comment by BobbyWibowo** [comment]
That's odd
I'm on Firefox 100.0.2 and it plays just fine for me, even with FLAC audio file
https://safe.fiery.me/v/rv5ZA.flac

Which OS are you on? 

---

<details>
  <summary>Firefox Desktop on Windows</summary>

![image](https://user-images.githubusercontent.com/9364930/170624962-488948c6-dfd9-4a90-8636-57b7077c6b94.png)

Last I checked there was no issue on my Linux boot either
</details>

<details>
  <summary>Firefox Android</summary>

![image](https://i.fiery.me/BnLs.png)
</details>

**Comment by BobbyWibowo** [comment]
> and when it works (on chrome) isn't responsive messing the whole player.

I can confirm that the waveform is seemingly not being automatically resized when user resize their browser window, however

Oddly enough, supposedly the CSS method they used should have done so (https://github.com/collab-project/videojs-wavesurfer/issues/132#issuecomment-804154183)

**Comment by BobbyWibowo** [comment]
For the responsiveness issue, should be fixed with https://github.com/BobbyWibowo/lolisafe/commit/3ec7e6c76c92d08c66babfbf224c421cdb9c7691

**Comment by perdedora** [comment]
> That's odd I'm on Firefox 100.0.2 and it plays just fine for me, even with FLAC audio file https://safe.fiery.me/v/rv5ZA.flac
> 
> Which OS are you on?

I'm on debian based distro. The problem was with my firefox profile, a clean one worked.

> For the responsiveness issue, should be fixed with [3ec7e6c](https://github.com/BobbyWibowo/lolisafe/commit/3ec7e6c76c92d08c66babfbf224c421cdb9c7691)

thanks, it worked.
