### ISSUE TITLE
Make usernames case-sensitive.

### ISSUE THREAD

**Issue by breachedvince** [BobbyWibowo/lolisafe#528]
Make the usernames case-sensitve when registering and logging in. You can have an account named " root " and another named " Root" or an account named " bobby " and another one named " Bobby " it is very annoying when dealing with stuff in admin panel etc.

**Comment by BobbyWibowo** [comment]
What you want isn't case-sensitivity, but the opposite
As it currently is, it already is case-sensitive, hence why you can create dupe users like that
But all operations involving users are also already case-sensitive and will thus only affect users with the exact same case

It's a very old custom so it's not going to change
But feel free to modify your own `register()` and `createUser()` functions in `authController.js` to do the duplicate username check case-insensitively
