### ISSUE TITLE
[Solved] Runs w/o errors, however not appearing on domain

### ISSUE THREAD

**Issue by GabenCrying** [BobbyWibowo/lolisafe#550]
rage@we:~/lolisafe$ yarn start
yarn run v1.22.19
$ node ./lolisafe.js
[2022-07-29 11:53:15] Starting lolisafe…
[2022-07-29 11:53:15] Created directory: /home/rage/lolisafe/database
[2022-07-29 11:53:15] Created directory: /home/rage/lolisafe/uploads
[2022-07-29 11:53:15] Created directory: /home/rage/lolisafe/uploads/chunks
[2022-07-29 11:53:15] Created directory: /home/rage/lolisafe/uploads/thumbs
[2022-07-29 11:53:15] Created directory: /home/rage/lolisafe/uploads/zips
[2022-07-29 11:53:15] Created directory: /home/rage/lolisafe/logs
[2022-07-29 11:53:16] lolisafe started on port 9999

It runs fine, just not appearing on the domain. Showing the default nginx page. Any ideas? 

Edit: It does appear under domain.com:9999

**Comment by BobbyWibowo** [comment]
It sounds like your nginx hasn't been properly configured to `proxy_pass` the default domain into lolisafe that runs on port 9999

Here's a rough example:

```conf
server {
    # ...
    location / {
        proxy_pass http://127.0.0.1:9999;
        proxy_redirect off;
        proxy_http_version 1.1;

        # Disable from-and-to buffering (redundant for lolisafe).
        proxy_buffering off;
        proxy_request_buffering off;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-NginX-Proxy true;

        # Increasing these may help with clients with very slow upload speeds.
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
        send_timeout 60s;
    }
    # ...
}
```

**Comment by GabenCrying** [comment]
> It sounds like your nginx hasn't been properly configured to `proxy_pass` the default domain into lolisafe that runs on port 9999
> 
> Here's a rough example:
> 
> ```
> server {
>     # ...
>     location / {
>         # Max upload size enforced on NGINX layer. Set accordingly.
>         client_max_body_size 10240m;
> 
>         proxy_pass http://127.0.0.1:9999;
>         proxy_redirect off;
>         proxy_http_version 1.1;
> 
>         # Disable from-and-to buffering (redundant for lolisafe).
>         proxy_buffering off;
>         proxy_request_buffering off;
> 
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection "upgrade";
>         proxy_set_header Host $host;
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         proxy_set_header X-Forwarded-Proto $scheme;
>         proxy_set_header X-Forwarded-Host $host;
>         proxy_set_header X-Forwarded-Port $server_port;
>         proxy_set_header X-NginX-Proxy true;
> 
>         # Increasing these may help with clients with very slow upload speeds.
>         proxy_connect_timeout 60s;
>         proxy_send_timeout 60s;
>         proxy_read_timeout 60s;
>         send_timeout 60s;
>     }
>     # ...
> }
> ```
Oh Lord You Genius, thank you so much!!!! This has been TROLLING the F**** out of me trying to figure it out. You rock

**Comment by BobbyWibowo** [comment]
Glad to know it's solved!
I'll be closing the issue then
