### ISSUE TITLE
Suggestion: Add some verbose output

### ISSUE THREAD

**Issue by Chiaki** [BobbyWibowo/lolisafe#61]
After update I've got an error:
```
[17:43:57] ESLintError in plugin "gulp-eslint"
Message:
    Failed with 8 errors
Details:
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false

[17:43:57] 'lint' errored after 4.11 s
[17:43:57] 'default' errored after 4.12 s
[17:43:57] The following tasks did not complete: lint:css
[17:43:57] Did you forget to signal async completion?
error Command failed with exit code 1.

```

It would be much easier to find a problem if verbose output for jobs was enabled.

Something like this.
**gulpfile.js**
https://github.com/BobbyWibowo/lolisafe/blob/a701a2ab47454795595298a6bc8c5cc90055e03e/gulpfile.js#L37
Add below: `.pipe(eslint.format('junit', process.stdout))`

https://github.com/BobbyWibowo/lolisafe/blob/a701a2ab47454795595298a6bc8c5cc90055e03e/gulpfile.js#L45
Change to: ` .pipe(stylelint({reporters:[{formatter:'verbose', console: true}]}))`

**Comment by BobbyWibowo** [comment]
I ended up using `stylish` formatter for ESLint, cause I'm pretty sure that's the default formatter even when running `eslint` manually from the terminal.
It's also a bit awkward that stylelint will always print something even when no errors occur, but I guess that works (as opposed to ESLint which outputs something only on errors).
